name: Alexa Shopping List Sync
version: "2409.259b"
slug: alexa_shopping_list
description: Alexa Shopping List synchronisation server
url: "https://github.com/mmstano/home-assistant-alexa-shopping-list"
arch:
  - aarch64
  - amd64
image: "mmstano/ha-alexa-shopping-list-sync"
startup: "services"
ports:
  4000/tcp: 4000
map:
  - type: data
    path: "/config"
    read_only: false
